### PR TITLE
Availability zone should be group (as per /instance endpoint) and not region

### PR DESCRIPTION
**Pull request by jennysivapalan**
In https://github.com/guardian/prism/pull/37 I incorrectly put the AZ group as region, I've followed the `/instance` endpoint and renamed it to group.

### CODE REVIEW

**Comment by sihil** [comment]
I think `group` might be left over from pre-aws code where AZ didn't make sense everywhere. Suggest we call it `az` or `availabilityZone` rather than group.

**Comment by sihil** [comment]
The ARN should really be region though. Is that available?

**Comment by jennysivapalan** [comment]
Sorry missed the comment..have updated to `availabilityZone`. 

No the region isn't returned. I just reserved some instances that were not tied to an AZ and those reservations do not seem to be returned at all 😞 . The field that determines if a reservation is tied to a region or not is called `Scope` on the AWS console, hopefully it will get added to the library in the future.

**Comment by sihil** [comment]
Have you checked on this recently @jennysivapalan ? Should this be merged regardless?

**Comment by jennysivapalan** [comment]
@sihil oh sorry - I tried to update the library a couple months ago as it did have region and scope in however it caused a fair few compilation issues and I didn't revisit it. We can probably merge this but I'm happy to try again as a Friday type task to see if I can update the library.

**Pull request closed without merging**
