### PR TITLE
Force jackson-databind version

### PR DESCRIPTION
**Pull request by regiskuckaertz**
Fixes the vulnerability issues reported by Snyk.

### CODE REVIEW

**Comment by philmcmahon** [comment]
LGTM 👍  but teamcity tests are complaining for some reason

**Comment by regiskuckaertz** [comment]
It won't be that easy 😆 Play Json also relies on it. I'll try upgrading Play to see if it helps.

**Comment by philmcmahon** [comment]
uh oh that might be a bit of a rabbit hole! @MatthewJWalls has been doing this with amiable recently so might be able to help with any weird dependency hell

**Comment by philmcmahon** [comment]
How did you get on with this @regiskuckaertz ?

**Comment by regiskuckaertz** [comment]
I first need to release the gu-management dependency, then update here, upgrade Play and then 🤞

**Pull request closed without merging**
